apiVersion: apps/v1
kind: Deployment
metadata:
  name: resolver-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resolver-service
  template:
    metadata:
      labels:
        app: resolver-service
    spec:
      containers:
        - name: resolver-service
          image: "hopr/resolver-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.resolverServerPort }}
          envFrom:
            - configMapRef:
                name: hopr-config
            - secretRef:
                name: hopr-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.config.resolverServerPort }}
            failureThreshold: 12
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.config.resolverServerPort }}
            initialDelaySeconds: 25
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.config.resolverServerPort }}
            initialDelaySeconds: 40
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: resolver-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: resolver-service
  ports:
    - port: {{ .Values.config.resolverServerPort }}
      targetPort: {{ .Values.config.resolverServerPort }}
